language: node_js
node_js:
  - 7.6
  - 8.4
  - 8.9
before_install:
  - echo 'Asia/Seoul' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - npm install mocha eslint -g
branches:
  only:
    - master
