language: node_js
node_js:
  - 7.6
  - 8.4
  - 8.9
branches:
  only:
    - master
before_install:
 - export TZ=Asia/Seoul
 - npm install -g istanbul
script:
 - npm run test-travis
 - npm run lint
after_script:
 - test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
